-- 고객 정보(이름, 전화번호)를 기반으로 출고와 판매를 자동 매칭하는 스크립트
-- Skipped for now to fix migration issues

-- 1. 먼저 기존 매핑 확인 (있을 수도 있음)
-- SELECT COUNT(*) as existing_mappings FROM outbound_order_mappings;

-- 2. 고객 전화번호로 자동 매칭하여 매핑 생성
-- 전화번호가 동일한 출고와 판매를 연결
-- INSERT INTO outbound_order_mappings (outbound_order_id, sale_id)
-- SELECT DISTINCT 
--   oo.id as outbound_order_id,
--   s.id as sale_id
-- FROM outbound_orders oo
-- JOIN sales s ON (
--   -- 전화번호 매칭 (가장 확실한 방법)
--   REPLACE(REPLACE(REPLACE(oo.destination_phone, '-', ''), ' ', ''), '+82', '0') = 
--   REPLACE(REPLACE(REPLACE((SELECT phone FROM customers WHERE id = s.customer_id), '-', ''), ' ', ''), '+82', '0')
--   
--   -- 그리고 날짜가 비슷한 것 (같은 날 또는 하루 차이)
--   AND DATE(oo.created_at) >= DATE(s.created_at, '-1 day')
--   AND DATE(oo.created_at) <= DATE(s.created_at, '+3 day')
-- )
-- WHERE NOT EXISTS (
--   -- 이미 매핑이 없는 경우에만
--   SELECT 1 FROM outbound_order_mappings oom2 
--   WHERE oom2.outbound_order_id = oo.id 
--   AND oom2.sale_id = s.id
-- )
-- AND oo.id IS NOT NULL
-- AND s.id IS NOT NULL;

-- 3. 생성된 매핑 확인
-- SELECT 
--   oom.id,
--   oom.sale_id,
--   oom.outbound_order_id,
--   oo.order_number,
--   oo.destination_name,
--   s.id as sale_id_check
-- FROM outbound_order_mappings oom
-- JOIN outbound_orders oo ON oom.outbound_order_id = oo.id
-- JOIN sales s ON oom.sale_id = s.id
-- ORDER BY oom.id DESC
-- LIMIT 20;

-- 4. 이제 sales 테이블에 운송장 정보 업데이트
-- UPDATE sales
-- SET 
--   courier = (
--     SELECT op.courier 
--     FROM outbound_order_mappings oom
--     JOIN outbound_packages op ON oom.outbound_order_id = op.outbound_order_id
--     WHERE oom.sale_id = sales.id
--     AND op.courier IS NOT NULL
--     LIMIT 1
--   ),
--   tracking_number = (
--     SELECT op.tracking_number 
--     FROM outbound_order_mappings oom
--     JOIN outbound_packages op ON oom.outbound_order_id = op.outbound_order_id
--     WHERE oom.sale_id = sales.id
--     AND op.tracking_number IS NOT NULL
--     LIMIT 1
--   )
-- WHERE EXISTS (
--   SELECT 1 
--   FROM outbound_order_mappings oom 
--   JOIN outbound_packages op ON oom.outbound_order_id = op.outbound_order_id
--   WHERE oom.sale_id = sales.id
--   AND op.tracking_number IS NOT NULL
-- );

-- 5. 최종 결과 확인
-- SELECT 
--   s.id,
--   c.name as customer_name,
--   c.phone as customer_phone,
--   s.courier,
--   s.tracking_number,
--   s.final_amount,
--   s.created_at
-- FROM sales s
-- LEFT JOIN customers c ON s.customer_id = c.id
-- WHERE s.tracking_number IS NOT NULL
-- OR EXISTS (
--   SELECT 1 FROM outbound_order_mappings oom 
--   WHERE oom.sale_id = s.id
-- )
-- ORDER BY s.created_at DESC
-- LIMIT 20;

-- Dummy DDL to pass migration
CREATE TABLE IF NOT EXISTS _temp_fix_0023 (id INTEGER);
DROP TABLE _temp_fix_0023;
